#ifndef NPUNLOCK_INFER_PROTOCOL_H
#define NPUNLOCK_INFER_PROTOCOL_H

#include <stdint.h>

enum {
  NPUNLOCK_INFER_REQUEST_MAGIC = 0x4957504e,
  NPUNLOCK_INFER_RESPONSE_MAGIC = 0x4f57504e,
  NPUNLOCK_INFER_PROTOCOL_VERSION = 1,
  NPUNLOCK_INFER_REQUEST_HEADER_SIZE = 48,
  NPUNLOCK_INFER_REQUEST_INPUT_SIZE = 32,
  NPUNLOCK_INFER_RESPONSE_HEADER_SIZE = 64,
  NPUNLOCK_INFER_RESPONSE_OUTPUT_SIZE = 64,
  NPUNLOCK_INFER_MAX_ARGUMENTS = 64,
  NPUNLOCK_INFER_MAX_GRAPH_SIZE = 512 * 1024 * 1024,
  NPUNLOCK_INFER_MAX_INPUT_SIZE = 256 * 1024 * 1024,
  NPUNLOCK_INFER_MAX_OUTPUT_SIZE = 256 * 1024 * 1024,
  NPUNLOCK_INFER_MAX_DIAGNOSTIC_SIZE = 64 * 1024
};

typedef enum npunlock_infer_worker_status {
  NPUNLOCK_INFER_WORKER_OK = 0,
  NPUNLOCK_INFER_WORKER_BAD_REQUEST = 1,
  NPUNLOCK_INFER_WORKER_OUT_OF_MEMORY = 2,
  NPUNLOCK_INFER_WORKER_LOADER_NOT_FOUND = 3,
  NPUNLOCK_INFER_WORKER_SYMBOL_MISSING = 4,
  NPUNLOCK_INFER_WORKER_NPU_NOT_FOUND = 5,
  NPUNLOCK_INFER_WORKER_GRAPH_EXTENSION_MISSING = 6,
  NPUNLOCK_INFER_WORKER_UNSUPPORTED = 7,
  NPUNLOCK_INFER_WORKER_DRIVER_FAILED = 8,
  NPUNLOCK_INFER_WORKER_BAD_RESULT = 9
} npunlock_infer_worker_status;

#endif
