#ifndef NPUNLOCK_IR_PROTOCOL_H
#define NPUNLOCK_IR_PROTOCOL_H

#include <stdint.h>

enum {
  NPUNLOCK_IR_REQUEST_MAGIC = 0x4957504e,
  NPUNLOCK_IR_RESPONSE_MAGIC = 0x4f57504e,
  NPUNLOCK_IR_PROTOCOL_VERSION = 1,
  NPUNLOCK_IR_REQUEST_HEADER_SIZE = 48,
  NPUNLOCK_IR_RESPONSE_HEADER_SIZE = 88,
  NPUNLOCK_IR_MAX_MESSAGE_SIZE = 256 * 1024 * 1024,
  NPUNLOCK_IR_MAX_RESULT_SIZE = 512 * 1024 * 1024,
  NPUNLOCK_IR_MAX_DIAGNOSTIC_SIZE = 64 * 1024
};

typedef enum npunlock_ir_worker_status {
  NPUNLOCK_IR_WORKER_OK = 0,
  NPUNLOCK_IR_WORKER_BAD_REQUEST = 1,
  NPUNLOCK_IR_WORKER_OUT_OF_MEMORY = 2,
  NPUNLOCK_IR_WORKER_LOADER_NOT_FOUND = 3,
  NPUNLOCK_IR_WORKER_SYMBOL_MISSING = 4,
  NPUNLOCK_IR_WORKER_NPU_NOT_FOUND = 5,
  NPUNLOCK_IR_WORKER_GRAPH_EXTENSION_MISSING = 6,
  NPUNLOCK_IR_WORKER_UNSUPPORTED = 7,
  NPUNLOCK_IR_WORKER_DRIVER_FAILED = 8,
  NPUNLOCK_IR_WORKER_BAD_RESULT = 9
} npunlock_ir_worker_status;

#endif
