#ifndef NPUNLOCK_MOVI_PROTOCOL_H
#define NPUNLOCK_MOVI_PROTOCOL_H

#include <stdint.h>

enum {
  NPUNLOCK_MOVI_REQUEST_MAGIC = 0x4b57504e,
  NPUNLOCK_MOVI_RESPONSE_MAGIC = 0x5257504e,
  NPUNLOCK_MOVI_PROTOCOL_VERSION = 1,
  NPUNLOCK_MOVI_REQUEST_HEADER_SIZE = 32,
  NPUNLOCK_MOVI_RESPONSE_HEADER_SIZE = 32,
  NPUNLOCK_MOVI_MAX_MESSAGE_SIZE = 64 * 1024 * 1024,
  NPUNLOCK_MOVI_MAX_RESULT_SIZE = 32 * 1024 * 1024
};

typedef enum npunlock_movi_stage {
  NPUNLOCK_MOVI_STAGE_COMPILE = 1,
  NPUNLOCK_MOVI_STAGE_ASSEMBLE = 2,
  NPUNLOCK_MOVI_STAGE_LINK = 3
} npunlock_movi_stage;

typedef enum npunlock_movi_worker_status {
  NPUNLOCK_MOVI_WORKER_OK = 0,
  NPUNLOCK_MOVI_WORKER_BAD_REQUEST = 1,
  NPUNLOCK_MOVI_WORKER_OUT_OF_MEMORY = 2,
  NPUNLOCK_MOVI_WORKER_LOAD_FAILED = 3,
  NPUNLOCK_MOVI_WORKER_SYMBOL_MISSING = 4,
  NPUNLOCK_MOVI_WORKER_BAD_RESULT = 5,
  NPUNLOCK_MOVI_WORKER_INTERNAL_ERROR = 6
} npunlock_movi_worker_status;

#endif
