#ifndef NPUNLOCK_RUN_PROTOCOL_H
#define NPUNLOCK_RUN_PROTOCOL_H

#include <stdint.h>

enum {
  NPUNLOCK_RUN_REQUEST_MAGIC = 0x5257504e,
  NPUNLOCK_RUN_RESPONSE_MAGIC = 0x5357504e,
  NPUNLOCK_RUN_PROTOCOL_VERSION = 1,
  NPUNLOCK_RUN_REQUEST_HEADER_SIZE = 32,
  NPUNLOCK_RUN_RESPONSE_HEADER_SIZE = 56,
  NPUNLOCK_RUN_MAX_GRAPH_SIZE = 512 * 1024 * 1024,
  NPUNLOCK_RUN_MAX_OUTPUT_SIZE = 64 * 1024 * 1024,
  NPUNLOCK_RUN_MAX_DIAGNOSTIC_SIZE = 64 * 1024
};

typedef enum npunlock_run_worker_status {
  NPUNLOCK_RUN_WORKER_OK = 0,
  NPUNLOCK_RUN_WORKER_BAD_REQUEST = 1,
  NPUNLOCK_RUN_WORKER_OUT_OF_MEMORY = 2,
  NPUNLOCK_RUN_WORKER_LOADER_NOT_FOUND = 3,
  NPUNLOCK_RUN_WORKER_SYMBOL_MISSING = 4,
  NPUNLOCK_RUN_WORKER_NPU_NOT_FOUND = 5,
  NPUNLOCK_RUN_WORKER_GRAPH_EXTENSION_MISSING = 6,
  NPUNLOCK_RUN_WORKER_UNSUPPORTED = 7,
  NPUNLOCK_RUN_WORKER_DRIVER_FAILED = 8,
  NPUNLOCK_RUN_WORKER_BAD_RESULT = 9
} npunlock_run_worker_status;

#endif
