#ifndef NPUNLOCK_VERSION_H
#define NPUNLOCK_VERSION_H

#define NPUNLOCK_VERSION_MAJOR 0
#define NPUNLOCK_VERSION_MINOR 1
#define NPUNLOCK_VERSION_PATCH 0
#define NPUNLOCK_VERSION_STRING "0.1.0"

#endif
